// Code generated by gen; DO NOT EDIT.

import { ApiError } from './errors.js'
import type {
  StandardResponse, ListOptions,
  PaginatedResponse, CursorPaginatedResponse,
  CreateAccountRequest, Account, EditAccountRequest, AddUserRequest, User, UserListOptions, 
  EditUserRequest, CreateRegionRequest, Region, EditRegionRequest, CreateStorageRequest, 
  Storage, StorageListOptions, EditStorageRequest, TestStorageBucketRequest, 
  CreateVolumeRequest, Volume, VolumeListOptions, EditVolumeRequest, 
  GenerateVolumeAPIKeysRequest, RevokeVolumeAPIKeyRequest, UpdateVolumeQuotaRequest, 
  AuditLog, AuditLogListOptions, ServiceNode, ClientSession, ClientSessionListOptions, 
  SessionSummary, DiscoverMetaResponse, DashboardStats, LicenseDetails,
} from '@mountos-app/admin-sdk'

function queryString(params: Record<string, string | number | undefined>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined)
  if (entries.length === 0) return ''
  return '?' + entries.map(([k, v]) => `${k}=${encodeURIComponent(v!)}`).join('&')
}

export interface ClientConfig {
  baseUrl?: string
  getHeaders?: () => Record<string, string> | Promise<Record<string, string>>
  onUnauthorized?: () => void
  /** Called on 401 before redirecting. Return true if token was refreshed and request should retry. */
  onRefreshToken?: () => Promise<boolean>
  /** Called on 403 step-up-required. Perform WebAuthn ceremony and return step-up token for retry. */
  onStepUpRequired?: () => Promise<string>
}

export class AdminClient {
  readonly baseUrl: string
  private readonly _getHeaders: () => Record<string, string> | Promise<Record<string, string>>
  private readonly _onUnauthorized?: () => void
  private readonly _onRefreshToken?: () => Promise<boolean>
  private readonly _onStepUpRequired?: () => Promise<string>
  private _refreshing: Promise<boolean> | null = null

  private _accounts?: AccountsResource
  private _users?: UsersResource
  private _regions?: RegionsResource
  private _storages?: StoragesResource
  private _volumes?: VolumesResource
  private _auditLogs?: AuditLogsResource
  private _serviceNodes?: ServiceNodesResource
  private _clientSessions?: ClientSessionsResource
  private _discover?: DiscoverResource
  private _dashboard?: DashboardResource
  private _license?: LicenseResource
  private _cache?: CacheResource

  constructor(config: ClientConfig = {}) {
    this.baseUrl = (config.baseUrl ?? '/api/v1').replace(/\/+$/, '')
    this._getHeaders = config.getHeaders ?? (() => ({}))
    this._onUnauthorized = config.onUnauthorized
    this._onRefreshToken = config.onRefreshToken
    this._onStepUpRequired = config.onStepUpRequired
  }

  get accounts(): AccountsResource {
    return (this._accounts ??= new AccountsResource(this))
  }

  get users(): UsersResource {
    return (this._users ??= new UsersResource(this))
  }

  get regions(): RegionsResource {
    return (this._regions ??= new RegionsResource(this))
  }

  get storages(): StoragesResource {
    return (this._storages ??= new StoragesResource(this))
  }

  get volumes(): VolumesResource {
    return (this._volumes ??= new VolumesResource(this))
  }

  get auditLogs(): AuditLogsResource {
    return (this._auditLogs ??= new AuditLogsResource(this))
  }

  get serviceNodes(): ServiceNodesResource {
    return (this._serviceNodes ??= new ServiceNodesResource(this))
  }

  get clientSessions(): ClientSessionsResource {
    return (this._clientSessions ??= new ClientSessionsResource(this))
  }

  get discover(): DiscoverResource {
    return (this._discover ??= new DiscoverResource(this))
  }

  get dashboard(): DashboardResource {
    return (this._dashboard ??= new DashboardResource(this))
  }

  get license(): LicenseResource {
    return (this._license ??= new LicenseResource(this))
  }

  get cache(): CacheResource {
    return (this._cache ??= new CacheResource(this))
  }

  async request<T>(method: string, path: string, body?: unknown, signal?: AbortSignal): Promise<T> {
    return this._doRequest(method, path, body, true, signal)
  }

  private async _doRequest<T>(method: string, path: string, body: unknown, allowRetry: boolean, signal?: AbortSignal): Promise<T> {
    const extra = await this._getHeaders()
    const headers: Record<string, string> = { ...extra }

    const init: RequestInit = { method, headers, credentials: 'include', signal }
    if (body !== undefined) {
      headers['Content-Type'] = 'application/json'
      init.body = JSON.stringify(body)
    }

    const res = await fetch(`${this.baseUrl}${path}`, init)

    if (res.status === 401) {
      if (allowRetry && this._onRefreshToken) {
        const refreshed = await this._coalesceRefresh()
        if (refreshed) return this._doRequest(method, path, body, false, signal)
      }
      this._onUnauthorized?.()
      throw new ApiError('unauthorized', 401)
    }

    if (res.status === 403 && allowRetry && this._onStepUpRequired) {
      const rb = await res.json().catch(() => ({})) as Record<string, unknown>
      if (rb.status === 'step-up-required') {
        const token = await this._onStepUpRequired()
        return this._doRetryWithStepUp(method, path, body, token, signal)
      }
      throw new ApiError((rb.message as string) ?? (rb.status as string) ?? 'forbidden', 403)
    }

    let json: StandardResponse<T>
    try {
      json = await res.json() as StandardResponse<T>
    } catch {
      throw new ApiError(res.statusText || 'request failed', res.status)
    }

    if (json.status !== 'success') {
      throw new ApiError(json.message, res.status, json.errorCode)
    }
    return json.data as T
  }

  private async _doRetryWithStepUp<T>(method: string, path: string, body: unknown, token: string, signal?: AbortSignal, refreshed = false): Promise<T> {
    const extra = await this._getHeaders()
    const headers: Record<string, string> = { ...extra, 'X-StepUp-Token': token }

    const init: RequestInit = { method, headers, credentials: 'include', signal }
    if (body !== undefined) {
      headers['Content-Type'] = 'application/json'
      init.body = JSON.stringify(body)
    }

    const res = await fetch(`${this.baseUrl}${path}`, init)

    if (res.status === 401 && !refreshed && this._onRefreshToken) {
      const ok = await this._coalesceRefresh()
      if (ok) return this._doRetryWithStepUp(method, path, body, token, signal, true)
      this._onUnauthorized?.()
      throw new ApiError('unauthorized', 401)
    }

    if (res.status === 401) {
      this._onUnauthorized?.()
      throw new ApiError('unauthorized', 401)
    }

    let json: StandardResponse<T>
    try {
      json = await res.json() as StandardResponse<T>
    } catch {
      throw new ApiError(res.statusText || 'request failed', res.status)
    }

    if (json.status !== 'success') {
      throw new ApiError(json.message, res.status, json.errorCode)
    }
    return json.data as T
  }

  private _coalesceRefresh(): Promise<boolean> {
    if (!this._refreshing) {
      this._refreshing = this._onRefreshToken!().finally(() => { this._refreshing = null })
    }
    return this._refreshing
  }
}

class AccountsResource {
  constructor(private client: AdminClient) {}

  create(req: CreateAccountRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/accounts/create', req)
  }

  list(opts?: ListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Account>> {
    return this.client.request('GET', `/accounts/list${queryString({ page: opts?.page, limit: opts?.limit })}`, undefined, signal)
  }

  get(accountId: number, signal?: AbortSignal): Promise<Account> {
    return this.client.request('GET', `/accounts/${accountId}`, undefined, signal)
  }

  edit(accountId: number, req: EditAccountRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/accounts/${accountId}/edit`, req)
  }

  lock(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/lock`)
  }

  unlock(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/unlock`)
  }

  activate(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/activate`)
  }

  deactivate(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/deactivate`)
  }
}

class UsersResource {
  constructor(private client: AdminClient) {}

  add(req: AddUserRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/users/add', req)
  }

  list(opts: UserListOptions, signal?: AbortSignal): Promise<PaginatedResponse<User>> {
    return this.client.request('GET', `/users/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(userId: number, signal?: AbortSignal): Promise<User> {
    return this.client.request('GET', `/users/${userId}`, undefined, signal)
  }

  edit(userId: number, req: EditUserRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/users/${userId}/edit`, req)
  }

  activate(userId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/users/${userId}/activate`)
  }

  deactivate(userId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/users/${userId}/deactivate`)
  }
}

class RegionsResource {
  constructor(private client: AdminClient) {}

  create(req: CreateRegionRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/regions/create', req)
  }

  list(opts?: ListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Region>> {
    return this.client.request('GET', `/regions/list${queryString({ page: opts?.page, limit: opts?.limit })}`, undefined, signal)
  }

  get(regionId: number, signal?: AbortSignal): Promise<Region> {
    return this.client.request('GET', `/regions/${regionId}`, undefined, signal)
  }

  edit(regionId: number, req: EditRegionRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/regions/${regionId}/edit`, req)
  }

  activate(regionId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/regions/${regionId}/activate`)
  }

  deactivate(regionId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/regions/${regionId}/deactivate`)
  }
}

class StoragesResource {
  constructor(private client: AdminClient) {}

  create(req: CreateStorageRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/storages/create', req)
  }

  list(opts: StorageListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Storage>> {
    return this.client.request('GET', `/storages/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(storageId: number, signal?: AbortSignal): Promise<Storage> {
    return this.client.request('GET', `/storages/${storageId}`, undefined, signal)
  }

  edit(storageId: number, req: EditStorageRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/storages/${storageId}/edit`, req)
  }

  activate(storageId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/storages/${storageId}/activate`)
  }

  deactivate(storageId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/storages/${storageId}/deactivate`)
  }

  testBucket(req: TestStorageBucketRequest): Promise<{ bucketExists: boolean; list: boolean; write: boolean; read: boolean; delete: boolean; multipart: boolean }> {
    return this.client.request('POST', '/storages/test-bucket', req)
  }
}

class VolumesResource {
  constructor(private client: AdminClient) {}

  create(req: CreateVolumeRequest): Promise<{ id: number; encryptionKey: string }> {
    return this.client.request('POST', '/volumes/create', req)
  }

  list(opts: VolumeListOptions, signal?: AbortSignal): Promise<PaginatedResponse<Volume>> {
    return this.client.request('GET', `/volumes/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`, undefined, signal)
  }

  get(volumeId: number, signal?: AbortSignal): Promise<Volume> {
    return this.client.request('GET', `/volumes/${volumeId}`, undefined, signal)
  }

  edit(volumeId: number, req: EditVolumeRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/volumes/${volumeId}/edit`, req)
  }

  lock(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/lock`)
  }

  unlock(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/unlock`)
  }

  activate(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/activate`)
  }

  deactivate(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/deactivate`)
  }

  generateAPIKeys(volumeId: number, req: GenerateVolumeAPIKeysRequest): Promise<{ apiKey: string; apiSecret: string }> {
    return this.client.request('POST', `/volumes/${volumeId}/api-keys/generate`, req)
  }

  revokeAPIKey(volumeId: number, req: RevokeVolumeAPIKeyRequest): Promise<void> {
    return this.client.request('POST', `/volumes/${volumeId}/api-keys/revoke`, req)
  }

  updateQuota(volumeId: number, req: UpdateVolumeQuotaRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/volumes/${volumeId}/quota`, req)
  }

  stats(volumeId: number): Promise<{ volumeId: string; diskSize: number; activeSize: number; size: number }> {
    return this.client.request('GET', `/volumes/${volumeId}/stats`)
  }
}

class AuditLogsResource {
  constructor(private client: AdminClient) {}

  list(opts?: AuditLogListOptions, signal?: AbortSignal): Promise<CursorPaginatedResponse<AuditLog>> {
    return this.client.request('GET', `/audit-logs/list${queryString({
      accountId: opts?.accountId,
      cursor: opts?.cursor,
      limit: opts?.limit,
      subject: opts?.subject,
    })}`, undefined, signal)
  }
}

class ServiceNodesResource {
  constructor(private client: AdminClient) {}

  list(regionId: number, serviceType?: string, status?: string, signal?: AbortSignal): Promise<ServiceNode[]> {
    return this.client.request('GET', `/regions/${regionId}/nodes` + queryString({ serviceType: serviceType, status: status }), undefined, signal)
  }

  stats(regionId: number, nodeId: string, signal?: AbortSignal): Promise<string> {
    return this.client.request('GET', `/regions/${regionId}/nodes/${encodeURIComponent(nodeId)}/stats`, undefined, signal)
  }
}

class ClientSessionsResource {
  constructor(private client: AdminClient) {}

  list(opts?: ClientSessionListOptions, signal?: AbortSignal): Promise<PaginatedResponse<ClientSession>> {
    return this.client.request('GET', `/client-sessions/list${queryString({ accountId: opts?.accountId, regionId: opts?.regionId, clientType: opts?.clientType, status: opts?.status, page: opts?.page, limit: opts?.limit })}`, undefined, signal)
  }

  get(sessionId: number, signal?: AbortSignal): Promise<ClientSession> {
    return this.client.request('GET', `/client-sessions/${sessionId}`, undefined, signal)
  }

  summary(accountId?: number, signal?: AbortSignal): Promise<SessionSummary[]> {
    return this.client.request('GET', `/client-sessions/summary${queryString({ accountId: accountId })}`, undefined, signal)
  }
}

class DiscoverResource {
  constructor(private client: AdminClient) {}

  meta(accessKeyId: string, signal?: AbortSignal): Promise<DiscoverMetaResponse> {
    return this.client.request('GET', `/discover/meta${queryString({ access_key_id: accessKeyId })}`, undefined, signal)
  }
}

class DashboardResource {
  constructor(private client: AdminClient) {}

  stats(accountId: number, signal?: AbortSignal): Promise<DashboardStats> {
    return this.client.request('GET', `/dashboard/stats${queryString({ accountId: accountId })}`, undefined, signal)
  }
}

class LicenseResource {
  constructor(private client: AdminClient) {}

  get(signal?: AbortSignal): Promise<LicenseDetails> {
    return this.client.request('GET', '/license', undefined, signal)
  }
}

class CacheResource {
  constructor(private client: AdminClient) {}

  refresh(): Promise<void> {
    return this.client.request('POST', '/cache/refresh')
  }
}
