// Code generated by gen; DO NOT EDIT.

import { ApiError } from './errors.js'
import type {
  StandardResponse, ListOptions,
  PaginatedResponse, CursorPaginatedResponse,
  CreateAccountRequest, Account, EditAccountRequest, AddUserRequest, User, UserListOptions, 
  EditUserRequest, CreateRegionRequest, Region, EditRegionRequest, CreateStorageRequest, 
  Storage, StorageListOptions, EditStorageRequest, CreateVolumeRequest, Volume, 
  VolumeListOptions, EditVolumeRequest, GenerateVolumeAPIKeysRequest, 
  RevokeVolumeAPIKeyRequest, UpdateVolumeQuotaRequest, AuditLog, AuditLogListOptions, 
  ServiceNode, DiscoverMetaResponse,
} from '@mountos-app/admin-sdk'

function queryString(params: Record<string, string | number | undefined>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined)
  if (entries.length === 0) return ''
  return '?' + entries.map(([k, v]) => `${k}=${encodeURIComponent(v!)}`).join('&')
}

export interface ClientConfig {
  baseUrl?: string
  getHeaders?: () => Record<string, string> | Promise<Record<string, string>>
  onUnauthorized?: () => void
}

export class AdminClient {
  readonly baseUrl: string
  private readonly _getHeaders: () => Record<string, string> | Promise<Record<string, string>>
  private readonly _onUnauthorized?: () => void

  private _accounts?: AccountsResource
  private _users?: UsersResource
  private _regions?: RegionsResource
  private _storages?: StoragesResource
  private _volumes?: VolumesResource
  private _auditLogs?: AuditLogsResource
  private _serviceNodes?: ServiceNodesResource
  private _discover?: DiscoverResource
  private _cache?: CacheResource

  constructor(config: ClientConfig = {}) {
    this.baseUrl = (config.baseUrl ?? '/api/proxy/v1').replace(/\/+$/, '')
    this._getHeaders = config.getHeaders ?? (() => ({}))
    this._onUnauthorized = config.onUnauthorized
  }

  get accounts(): AccountsResource {
    return (this._accounts ??= new AccountsResource(this))
  }

  get users(): UsersResource {
    return (this._users ??= new UsersResource(this))
  }

  get regions(): RegionsResource {
    return (this._regions ??= new RegionsResource(this))
  }

  get storages(): StoragesResource {
    return (this._storages ??= new StoragesResource(this))
  }

  get volumes(): VolumesResource {
    return (this._volumes ??= new VolumesResource(this))
  }

  get auditLogs(): AuditLogsResource {
    return (this._auditLogs ??= new AuditLogsResource(this))
  }

  get serviceNodes(): ServiceNodesResource {
    return (this._serviceNodes ??= new ServiceNodesResource(this))
  }

  get discover(): DiscoverResource {
    return (this._discover ??= new DiscoverResource(this))
  }

  get cache(): CacheResource {
    return (this._cache ??= new CacheResource(this))
  }

  async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const extra = await this._getHeaders()
    const headers: Record<string, string> = { ...extra }

    const init: RequestInit = { method, headers, credentials: 'include' }
    if (body !== undefined) {
      headers['Content-Type'] = 'application/json'
      init.body = JSON.stringify(body)
    }

    const res = await fetch(`${this.baseUrl}${path}`, init)

    if (res.status === 401) {
      this._onUnauthorized?.()
      throw new ApiError('unauthorized', 401)
    }

    let json: StandardResponse<T>
    try {
      json = await res.json() as StandardResponse<T>
    } catch {
      throw new ApiError(res.statusText || 'request failed', res.status)
    }

    if (json.status !== 'success') {
      throw new ApiError(json.message, res.status, json.errorCode)
    }
    return json.data as T
  }
}

class AccountsResource {
  constructor(private client: AdminClient) {}

  create(req: CreateAccountRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/accounts/create', req)
  }

  list(opts?: ListOptions): Promise<PaginatedResponse<Account>> {
    return this.client.request('GET', `/accounts/list${queryString({ page: opts?.page, limit: opts?.limit })}`)
  }

  get(accountId: number): Promise<Account> {
    return this.client.request('GET', `/accounts/${accountId}`)
  }

  edit(accountId: number, req: EditAccountRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/accounts/${accountId}/edit`, req)
  }

  lock(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/lock`)
  }

  unlock(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/unlock`)
  }

  activate(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/activate`)
  }

  deactivate(accountId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/accounts/${accountId}/deactivate`)
  }
}

class UsersResource {
  constructor(private client: AdminClient) {}

  add(req: AddUserRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/users/add', req)
  }

  list(opts: UserListOptions): Promise<PaginatedResponse<User>> {
    return this.client.request('GET', `/users/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`)
  }

  get(userId: number): Promise<User> {
    return this.client.request('GET', `/users/${userId}`)
  }

  edit(userId: number, req: EditUserRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/users/${userId}/edit`, req)
  }

  activate(userId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/users/${userId}/activate`)
  }

  deactivate(userId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/users/${userId}/deactivate`)
  }
}

class RegionsResource {
  constructor(private client: AdminClient) {}

  create(req: CreateRegionRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/regions/create', req)
  }

  list(opts?: ListOptions): Promise<PaginatedResponse<Region>> {
    return this.client.request('GET', `/regions/list${queryString({ page: opts?.page, limit: opts?.limit })}`)
  }

  get(regionId: number): Promise<Region> {
    return this.client.request('GET', `/regions/${regionId}`)
  }

  edit(regionId: number, req: EditRegionRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/regions/${regionId}/edit`, req)
  }

  activate(regionId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/regions/${regionId}/activate`)
  }

  deactivate(regionId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/regions/${regionId}/deactivate`)
  }
}

class StoragesResource {
  constructor(private client: AdminClient) {}

  create(req: CreateStorageRequest): Promise<{ id: number }> {
    return this.client.request('POST', '/storages/create', req)
  }

  list(opts: StorageListOptions): Promise<PaginatedResponse<Storage>> {
    return this.client.request('GET', `/storages/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`)
  }

  get(storageId: number): Promise<Storage> {
    return this.client.request('GET', `/storages/${storageId}`)
  }

  edit(storageId: number, req: EditStorageRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/storages/${storageId}/edit`, req)
  }

  activate(storageId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/storages/${storageId}/activate`)
  }

  deactivate(storageId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/storages/${storageId}/deactivate`)
  }
}

class VolumesResource {
  constructor(private client: AdminClient) {}

  create(req: CreateVolumeRequest): Promise<{ id: number; encryptionKey: string }> {
    return this.client.request('POST', '/volumes/create', req)
  }

  list(opts: VolumeListOptions): Promise<PaginatedResponse<Volume>> {
    return this.client.request('GET', `/volumes/list${queryString({ accountId: opts.accountId, page: opts.page, limit: opts.limit })}`)
  }

  get(volumeId: number): Promise<Volume> {
    return this.client.request('GET', `/volumes/${volumeId}`)
  }

  edit(volumeId: number, req: EditVolumeRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/volumes/${volumeId}/edit`, req)
  }

  lock(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/lock`)
  }

  unlock(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/unlock`)
  }

  activate(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/activate`)
  }

  deactivate(volumeId: number): Promise<{ id: number }> {
    return this.client.request('POST', `/volumes/${volumeId}/deactivate`)
  }

  generateAPIKeys(volumeId: number, req: GenerateVolumeAPIKeysRequest): Promise<{ apiKey: string; apiSecret: string }> {
    return this.client.request('POST', `/volumes/${volumeId}/api-keys/generate`, req)
  }

  revokeAPIKey(volumeId: number, req: RevokeVolumeAPIKeyRequest): Promise<void> {
    return this.client.request('POST', `/volumes/${volumeId}/api-keys/revoke`, req)
  }

  updateQuota(volumeId: number, req: UpdateVolumeQuotaRequest): Promise<{ id: number }> {
    return this.client.request('PUT', `/volumes/${volumeId}/quota`, req)
  }

  stats(volumeId: number): Promise<{ volumeId: string; diskSize: number; activeSize: number; size: number }> {
    return this.client.request('GET', `/volumes/${volumeId}/stats`)
  }
}

class AuditLogsResource {
  constructor(private client: AdminClient) {}

  list(opts?: AuditLogListOptions): Promise<CursorPaginatedResponse<AuditLog>> {
    return this.client.request('GET', `/audit-logs/list${queryString({
      accountId: opts?.accountId,
      cursor: opts?.cursor,
      limit: opts?.limit,
      subject: opts?.subject,
    })}`)
  }
}

class ServiceNodesResource {
  constructor(private client: AdminClient) {}

  list(regionId: number): Promise<ServiceNode[]> {
    return this.client.request('GET', `/regions/${regionId}/nodes`)
  }

  drain(regionId: number, nodeId: string): Promise<void> {
    return this.client.request('POST', `/regions/${regionId}/nodes/${encodeURIComponent(nodeId)}/drain`)
  }

  activate(regionId: number, nodeId: string): Promise<void> {
    return this.client.request('POST', `/regions/${regionId}/nodes/${encodeURIComponent(nodeId)}/activate`)
  }

  remove(regionId: number, nodeId: string): Promise<void> {
    return this.client.request('DELETE', `/regions/${regionId}/nodes/${encodeURIComponent(nodeId)}`)
  }
}

class DiscoverResource {
  constructor(private client: AdminClient) {}

  meta(accessKeyId: string): Promise<DiscoverMetaResponse> {
    return this.client.request('GET', `/discover/meta${queryString({ access_key_id: accessKeyId })}`)
  }
}

class CacheResource {
  constructor(private client: AdminClient) {}

  refresh(): Promise<void> {
    return this.client.request('POST', '/cache/refresh')
  }
}
