export type {
  Ref,
  Account,
  User,
  Region,
  Storage,
  Volume,
  Fork,
  AuditLog,
  ServiceNode,
  DiscoverMetaResponse,
  DiscoverEndpoint,
  DashboardStats,
  RegionVolumeMetrics,
  CreateAccountRequest,
  EditAccountRequest,
  AddUserRequest,
  EditUserRequest,
  CreateRegionRequest,
  EditRegionRequest,
  CreateStorageRequest,
  EditStorageRequest,
  TestStorageBucketRequest,
  CreateVolumeRequest,
  EditVolumeRequest,
  GenerateVolumeAPIKeysRequest,
  RevokeVolumeAPIKeyRequest,
  RevokeVolumeAPIKeysByUserRequest,
  DeactivateVolumeRequest,
  UpdateVolumeQuotaRequest,
  ListOptions,
  PaginatedResponse,
  CursorPaginatedResponse,
  PaginationMeta,
  UserListOptions,
  StorageListOptions,
  VolumeListOptions,
  AuditLogListOptions,
  RegionAuditLogListOptions,
  ClientSession,
  ClientSessionListOptions,
  SessionSummary,
  StandardResponse,
  LicenseDetails,
  LicenseStatus,
  LicenseType,
} from '@mountos-app/admin-sdk'

export { ApiError } from './errors.js'
export { AdminClient, type ClientConfig } from './client.gen.js'
